#ifndef COOGLEIOT_CONFIG_H
#define COOGLEIOT_CONFIG_H

#define COOGLEIOT_DEBUG

#define COOGLEIOT_VERSION "0.1b"

#define COOGLEIOT_STATUS_INIT 500
#define COOGLEIOT_STATUS_WIFI_INIT 250
#define COOGLEIOT_STATUS_MQTT_INIT 100

#define COOGLEIOT_MAGIC_BYTES "ciot"
#define COOGLEIOT_AP "COOGLEIOT_"
#define COOGLEIOT_AP_DEFAULT_PASSWORD "coogleiot"
#define COOGLEIOT_DEFAULT_MQTT_CLIENT_ID "coogleIoT"

#define COOGLEIOT_DEFAULT_MQTT_PORT 1883

#define COOGLEIOT_TIMEZONE_OFFSET ((3600 * 5) * -1) // Default Timezone is -5 UTC (America/New York)
#define COOGLEIOT_DAYLIGHT_OFFSET 0 // seconds

#define COOGLEIOT_NTP_SERVER_1 "pool.ntp.org"
#define COOGLEIOT_NTP_SERVER_2 "time.nist.gov"
#define COOGLEIOT_NTP_SERVER_3 "time.google.com"

#define COOGLEIOT_FIRMWARE_UPDATE_CHECK_MS 54000000  // 15 Minutes in Milliseconds

#define COOGLEIOT_DNS_PORT 53

#define COOGLE_EEPROM_EEPROM_SIZE 1024

#define COOGLEIOT_WEBSERVER_PORT 80

#ifdef COOGLEIOT_DEBUG
#define COOGLEEEPROM_DEBUG
#endif

#endif
